 Ext.define('YSYS.model.board.BoardModel', {
    extend: 'Ext.data.Model',
  
	fields: [
		'bb_id',
		'bb_nm',
		'bb_typ_cd',
		'bbm_id',
		'ch_div_cd',
		'ch_div_nm',
		'bbm_titl',
		'bbm_writer',
		'bbm_ctt',
		{name: 'bbm_expr_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime},
		//'bbm_expr_dtm',
		'hrnk_bbm_seq',
		'lck_user_id',
		'lck_user_nm',
		{name: 'lck_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime},
		//'lck_dtm',
		'bbm_hits_cnt',
		'noti_yn',
		'urg_yn',
		'chg_lck_yn',
		'bbm_del_yn',
		'inputr_id',
		'inputr_nm',
		{name: 'input_dt', mapping: 'input_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime_hi},
		{name: 'input_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime},
		//'input_dtm',
		'updtr_id',
		'updtr_nm',
		{name: 'updt_dt', mapping: 'updt_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime_hi},
		{name: 'updt_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime},
		//'updt_dtm',
		'delr_id', 
		{name: 'del_dt', mapping: 'del_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime_hi},
		{name: 'del_dtm', convert: YSYS.ux.FieldConvert.dateFormatDateTime},
		//'del_dtm', 
		'reply_id',
		'reply', 
		'step' ,
		'open_yn',
		'cmnt_count',
		'file_count'
	]
 });
